[project]
name = "asyncio-samples-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "asyncio>=3.4.3",
    "requests>=2.32.4",
]
